title: SeaCO<sub>2</sub> lab @ NIOZ Texel
description: Marine carbonate chemistry at the NIOZ Royal Netherlands Institute for Sea Research

baseurl: /
color-scheme: "#177192"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
